apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6r6l
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-6r6l@sha256:993da7e660d723c6bac489cc2210f09e68c755efacc14bc4c8c5b61cf33dc400
        name: my-nodejs
        resources: {}
status: {}
